name: rails                                  # workflow name

on:
  push:                                       
    branches:                                 # similar to "only" in GitLab
      - main

jobs:
  bundler-audit:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
  
        - run: docker run --rm $(pwd):/src -w /src hysnsec/bundle-audit check --format json --output bundle-audit-output.json
  
        - uses: actions/upload-artifact@v4
          with:
            name: bundler-audit
            path: bundle-audit-output.json
          if: always()                        # what is this for?
